namespace SpriteKind {
    export const egg = SpriteKind.create()
    export const cracked1 = SpriteKind.create()
    export const monster = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.cracked1, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        otherSprite.setKind(SpriteKind.cracked1)
        otherSprite.setImage(assets.image`crack 2`)
        sprites.destroy(otherSprite, effects.clouds, 200)
        info.changeScoreBy(1)
        info.changeCountdownBy(1)
        if (info.score() < 9) {
            Monster = sprites.create(img`
                . . f f f . . . . . . . . . . . 
                f f f c c . . . . . . . . f f f 
                f f c c c . c c . . . f c b b c 
                f f c 3 c c 3 c c f f b b b c . 
                f f c 3 b c 3 b c f b b c c c . 
                f c b b b b b b c f b c b c c . 
                c c 1 b b b 1 b c b b c b b c . 
                c b b b b b b b b b c c c b c . 
                c b 1 f f 1 c b b c c c c c . . 
                c f 1 f f 1 f b b b b f c . . . 
                f f f f f f f b b b b f c . . . 
                f f 2 2 2 2 f b b b b f c c . . 
                . f 2 2 2 2 2 b b b c f . . . . 
                . . f 2 2 2 b b b c f . . . . . 
                . . . f f f f f f f . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, SpriteKind.monster)
            Monster.setPosition(-10, -10)
            pause(200)
            Monster.follow(Main_character, 90)
        }
    }
})
function animate_charachter () {
    animation.runImageAnimation(
    Main_character,
    [img`
        ........................................
        ........................................
        ........................................
        ........................................
        ..............fffffffff.................
        ............fffffffffffff...............
        ...........fffffffffffffff..............
        ..........fffffffffffffffff.............
        .........ffffffffffffffffbff............
        .........fffffffffffffffbbbf............
        .........fffffffffffffffbbbf............
        ........ffffffffffffdffbbcbbf...........
        ........fffffffffffdddfbbcbbf...........
        ........ffffffffffdddddbbcbbf...........
        ........fffffddffddddddbbcbbff..........
        ........ff.fdffdfddffddbbcbbff..........
        ........ff.fdffddddffddbbcbbff..........
        ........f.fddffddddffddbbcbbff..........
        ..........fddddddddddddbbcbbff..........
        ..........fdddd2dd2ddddbbcbbff..........
        ........3333dddd22dddddbbcbbff..........
        .......333333dddddddddfbbcbbff..........
        .......333333fffdddddffbbcbbff..........
        .......3333ddfddddddddabbcbbf3..........
        .......f33dd111dd1111adbbcbb33ff........
        .......ffff1111dd111a1dbbcbb3fffff......
        ........fff111111111acccccccccfffffff...
        .........fff11111111acccccccccffffff....
        ............fddddddadf.ddddd.ffffff.....
        ............ffffffffff.ddddd...fff......
        ...........ffffffffffffddddd............
        ............dddd..dddd..bdb.............
        ............dddd..dddd..bbb.............
        ...........dddd....ddd..................
        ...........dddd....dddd.................
        ...........dddd....dddd.................
        ...........3333....3333.................
        ...........33333..33333.................
        ........................................
        ........................................
        `,img`
        ........................................
        ........................................
        ........................................
        ........................................
        ..............fffffffffff...............
        ............fffffffffffffff.............
        ...........fffffffffffffffff............
        ..........fffffffffffffffffff...........
        .........fffffffffffffffffffff..........
        .........fffffffffffffffffffff..........
        .........fffffffffffffffffffff..........
        ........ffffffffffffffdffffffff.........
        ........fffffffffffffdddfffffff.........
        ........ffffffffffffdddddffffff.........
        ........fffffffddffdddddddffffff........
        ........ffffdfd22dfdd22dddffffff........
        ........ffffdfd22dddd22dddfdffff........
        ....9...f.fdfdd22dddd22dddfddfff........
        ..99......fdfddddddddddddfdddfff........
        .9........fdfddddddddddddfdddfff........
        9..9....333333ddddffddddddddffff........
        ..9....33333333dddddddddffffffff........
        .9.....33333333fffdddddfffffffff........
        .9.....333333ddfdddddddccfffffff........
        .9.....f3f33dd111dd1111ccfccffffff......
        9.....bbbbbbbbbbbbbbbbbccddddfffffff....
        ....bbbbbbbbbbbbbbbbbbbccddddccffffffff.
        ...bbbbccccccccccccccccccdddddcfffffff..
        ....bbbbbbbbbbbbbbbbbbbccddddccffffff...
        ......bbbbbbbbbbbbbbbbbccdddd..fffff....
        .9.........ffffffffffffccddd............
        .99.........dddddddddddccdb.............
        ...999......ddddddddddddbbb.............
        99.........dddddd..ddddd................
        .9.........dddddd..dddddd...............
        ..9........dddddd..dddddd...............
        ...........333333..333333...............
        ...........33333333333333...............
        ........................................
        ........................................
        `,img`
        ........................................
        ........................................
        ........................................
        ........................................
        ..............fffffffff.................
        ............fffffffffffff...............
        ...........fffffffffffffff..............
        ..........fffffffffffffffff.............
        .........ffffffffffffffffbff............
        .........fffffffffffffffbbbf............
        .........fffffffffffffffbbbf............
        ........ffffffffffffdffbbcbbf...........
        ........fffffffffffdddfbbcbbf...........
        ........ffffffffffdddddbbcbbf...........
        ........fffffddffddddddbbcbbff..........
        ........ff.fdffdfddffddbbcbbff..........
        ........ff.fdffddddffddbbcbbff..........
        ........f.fddffddddffddbbcbbff..........
        ..........fddddddddddddbbcbbff..........
        ..........fdddd2dd2ddddbbcbbff..........
        ........3333dddd22dddddbbcbbff..........
        .......333333dddddddddfbbcbbff..........
        .......333333fffdddddffbbcbbff..........
        .......3333ddfddddddddabbcbbf3..........
        .......f33dd111dd1111adbbcbb33ff........
        .......ffff1111dd111a1dbbcbb3fffff......
        ........fff111111111acccccccccfffffff...
        .........fff11111111acccccccccffffff....
        ............fddddddadf.ddddd.ffffff.....
        ............ffffffffff.ddddd...fff......
        ...........ffffffffffffddddd............
        ............dddd..dddd..bdb.............
        ............dddd..dddd..bbb.............
        ...........dddd....ddd..................
        ...........dddd....dddd.................
        ...........dddd....dddd.................
        ...........3333....3333.................
        ...........33333..33333.................
        ........................................
        ........................................
        `],
    100,
    false
    )
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.egg, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        otherSprite.setKind(SpriteKind.cracked1)
        otherSprite.setImage(assets.image`crack 1`)
        pause(100)
    }
})
let Egg: Sprite = null
let Monster: Sprite = null
let Main_character: Sprite = null
game.splash("Welcome to Moster Bag")
tiles.setCurrentTilemap(tilemap`level2`)
Main_character = sprites.create(img`
    ........................................
    ........................................
    ........................................
    ........................................
    ..............fffffffff.................
    ............fffffffffffff...............
    ...........fffffffffffffff..............
    ..........fffffffffffffffff.............
    .........ffffffffffffffffbff............
    .........fffffffffffffffbbbf............
    .........fffffffffffffffbbbf............
    ........ffffffffffffdffbbcbbf...........
    ........fffffffffffdddfbbcbbf...........
    ........ffffffffffdddddbbcbbf...........
    ........fffffddffddddddbbcbbff..........
    ........ff.fdffdfddffddbbcbbff..........
    ........ff.fdffddddffddbbcbbff..........
    ........f.fddffddddffddbbcbbff..........
    ..........fddddddddddddbbcbbff..........
    ..........fdddd2dd2ddddbbcbbff..........
    ........3333dddd22dddddbbcbbff..........
    .......333333dddddddddfbbcbbff..........
    .......333333fffdddddffbbcbbff..........
    .......3333ddfddddddddabbcbbf3..........
    .......f33dd111dd1111adbbcbb33ff........
    .......ffff1111dd111a1dbbcbb3fffff......
    ........fff111111111acccccccccfffffff...
    .........fff11111111acccccccccffffff....
    ............fddddddadf.ddddd.ffffff.....
    ............ffffffffff.ddddd...fff......
    ...........ffffffffffffddddd............
    ............dddd..dddd..bdb.............
    ............dddd..dddd..bbb.............
    ...........dddd....ddd..................
    ...........dddd....dddd.................
    ...........dddd....dddd.................
    ...........3333....3333.................
    ...........33333..33333.................
    ........................................
    ........................................
    `, SpriteKind.Player)
controller.moveSprite(Main_character, 100, 100)
scene.cameraFollowSprite(Main_character)
info.startCountdown(60)
info.setScore(0)
game.onUpdate(function () {
    if (controller.A.isPressed()) {
        animate_charachter()
    }
})
game.onUpdateInterval(1000, function () {
    Egg = sprites.create(assets.image`uncracked`, SpriteKind.egg)
    Egg.setPosition(randint(0, 160), randint(0, 160))
})
